/*
 * This source file was generated by the Gradle 'init' task
 */
package cbradford.aoc2024;

import org.junit.Test;
import static org.junit.Assert.*;

public class TrailSearchTest {
    @Test public void appHasAGreeting() {
        TrailSearch classUnderTest = new TrailSearch();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
